{{- if and .Values.privateKey.value (not .Values.privateKey.existingSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: github-exporter-private-key
type: Opaque
data:
  private-key.pem: {{ .Values.privateKey.value | b64enc }}
{{- end }}