{{- if and .Values.privateKey.value (not .Values.privateKey.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "github-exporter.name" . }}-private-key
  labels:
    {{- include "github-exporter.labels" . | nindent 4 }}
type: Opaque
stringData:
  private-key.pem: |
    {{- .Values.privateKey.value | nindent 4 }}
{{- end }}
